# Generated by Django 5.1.4 on 2025-02-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0004_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='experience_level',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('Experienced', 'Experienced')], default='Fresher', max_length=15),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='experience_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
