# Generated by Django 5.1.4 on 2025-02-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0005_jobpost_experience_level_jobpost_experience_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
