# Generated by Django 5.1.4 on 2025-02-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0006_candidate_company_name_alter_candidate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='apply_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
