# Generated by Django 5.1.4 on 2025-02-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0007_jobpost_apply_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='jobpost',
            name='requirements',
            field=models.ManyToManyField(blank=True, to='job_app.requirement'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='responsibilities',
            field=models.ManyToManyField(blank=True, to='job_app.responsibility'),
        ),
    ]
