# Generated by Django 5.1.4 on 2025-02-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0008_requirement_responsibility_jobpost_requirements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='responsibilities',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Responsibility',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
